const data = [
  {
    "id": "1",
    "category": "For Men",
    "price": "12$",
    "sale": "30%",
    "brand": "Louis Vuitton",
    "size": "SM/LG",
    "name": "A-Line Shirt, Cotton Fabric.",
    "reviews": "3",
    "description": "Breathable cotton A-line cut—casual layering with a semi-formal edge.",
    "image": "https://www.urbanofashion.com/cdn/shop/files/shirtsolreg-02-slblue-1.jpg?v=1748263649"
  },
  {
    "id": "2",
    "category": "For Men",
    "price": "6$",
    "sale": "20%",
    "brand": "GUCCI",
    "size": "XL/LG",
    "name": "Check Style Shirt.",
    "reviews": "4",
    "description": "Stylish checked cotton shirt—ideal for weekend outings.",
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQDQmHl9AWrdXWiNGB6LYU_lXTH_G53OeHJJqoKiS8OqKbudIGk8kCQAhU-Y3-baR7epKF1hLB8DdEMf0uvZGpuMlzA23Iks9A6kZWGgOkfamBK3JUl76NBN6o&usqp=CAc"
  },
  {
    "id": "3",
    "category": "For Men",
    "price": "9$",
    "sale": "40%",
    "brand": "ZARA",
    "size": "SM/LG",
    "name": "Plain Shirt.",
    "reviews": "2",
    "description": "Minimalist lightweight cotton—great for layering any season.",
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTqCefrWdLdx8FRZQbnPXaD1O7c06EPYJchABoD36AbhZpdVaO0IQ8oRpgcwvSjCfRI6h6nZuTO7IGAORbZeA6lJYxffcjt05Ajqich7M60_QVf5Fp1TDmU"
  },
  {
    "id": "4",
    "category": "For Men",
    "price": "10$",
    "sale": "60%",
    "brand": "Louis Vuitton",
    "size": "MD/LG",
    "name": "Just Black Shirt",
    "reviews": "4",
    "description": "Classic black dress shirt with structured collar—perfect evening wear.",
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQLFfncBsYG9x1vqOWrwy9vMbsCTGGInJMtsmSTSX2e-7cc2-pH6c6GMprDU88P4y-CabnR6S7V3ZfSQZDMzHzCVxq92XYPVvjMrdwequJDjny5deNx2E2Y7A",
    "additional_images": ["https://bobbyjones.com/products/short_sleeve_back.jpg"]
  },
  {
    "id": "5",
    "category": "For Men",
    "price": "11$",
    "sale": "35%",
    "brand": "GUCCI",
    "size": "SM/LG/XL",
    "name": "Sky Blue Plain Shirt.",
    "reviews": "5",
    "description": "Sky-blue cotton shirt—smart casual or office-ready.",
    "image": "https://www.beyoung.in/api/cache/catalog/products/new_checked_shirt_image_9_12_2022/sky_blue_plain_cotton_shirts_base_700x933.jpg",
    "additional_images": ["https://images.llbean.com/is/image/llbean/pima_cotton_back2.jpg"]
  },
  {
    "id": "6",
    "category": "For Men",
    "price": "14$",
    "sale": "70%",
    "brand": "ZARA",
    "size": "SM/LG",
    "name": "3 Color Shirt.",
    "reviews": "3",
    "description": "Colorblocked casual shirt in three shades—bold and trendy.",
    "image": "https://m.media-amazon.com/images/I/418-NWHX5aL.jpg",
    "additional_images": ["https://walmart.com/ip/shirt_blue_back.jpg"]
  },
  {
    "id": "7",
    "category": "For Men",
    "price": "13$",
    "sale": "50%",
    "brand": "H&M",
    "size": "MD/LG",
    "name": "Casual Floral Shirt",
    "reviews": "2",
    "description": "Floral-printed casual shirt—lightweight cotton summer essential.",
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS41nr6TWZ1RlGOPH-z9JE3y4MVrEcCe_euUpE24nFxiGkdAXG9v36a0j6ZML0zhZ7owjO0XW8lgPfolsJFTMp37LRbPRA0NsB4sNRVWWg",
    "additional_images": ["https://freshcleantees.com/products/black_tee_back.jpg"]
  },
  {
    "id": "9",
    "category": "For Men",
    "price": "8$",
    "sale": "45%",
    "brand": "Puma",
    "size": "SM/MD",
    "name": "Printed Casual Shirt",
    "reviews": "3",
    "description": "Printed casual for athleisure days—sporty and comfortable.",
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTxOOCHP35hPcLkDLDZpMpzOjYo4FKTbmJ35hue6hwtDrw_yJ4XNVH8A_q8eg9s87OHxruWBRt5H8QoF_2U5gKGhIZ2c9feHv0HlZKvVwFh_2Ghm-0oOZrrcw"
  },
  {
    "id": "10",
    "category": "For Men",
    "price": "9$",
    "sale": "20%",
    "brand": "Reebok",
    "size": "XL",
    "name": "Cotton Comfort Shirt",
    "reviews": "5",
    "description": "Soft cotton comfort shirt—ideal for easy everyday wear.",
    "image": "https://img.tatacliq.com/images/i19//437Wx649H/MP000000023095988_437Wx649H_202407281221171.jpeg"
  },
  {
    "id": "11",
    "category": "For Women",
    "price": "80$",
    "sale": "20%",
    "brand": "FabIndia",
    "size": "SM/LG",
    "name": "Silk Saree with Zari Border",
    "reviews": "5",
    "description": "Traditional silk saree perfect for festive occasions with rich zari work.",
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTS22vWxVXGava3NwTNZg24lWyDVRcuObj7haetPImudqk-JGwKJEk8SByilHJiyPuiA6PaiTpjtIXPIOAnQM8OYWmdDvdIgIXMtiGXEVts"
  },
  {
    "id": "12",
    "category": "For Women",
    "price": "65$",
    "sale": "15%",
    "brand": "Biba",
    "size": "M/LG",
    "name": "Anarkali Kurta Set",
    "reviews": "3",
    "description": "Elegant Anarkali with dupatta—great for casual and festive wear.",
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTT-6NNthJ2R-WZUlhYf-kGCNo6dQmLSx6ymxBfqzeoePU63RXsaB3WcaP8OlL30uD1Fi1iJI3VfYTPACpBO1KMc2EmDbPntFMDGvRNd2Fw"
  },
  {
    "id": "13",
    "category": "For Women",
    "price": "95$",
    "sale": "25%",
    "brand": "W",
    "size": "SM/MD/LG",
    "name": "Designer Lehenga Choli",
    "reviews": "4",
    "description": "Stylish lehenga with intricate embroidery and modern fit.",
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQMJE5684DfVDH_5tvD0GmS5dzaeHoQ-4zfJTYH6siJ4VYsxto2tmDW7e_ctyiz095_lDXXapdew0Yd-ZpMA8QTFoCd3Ntid6OtVycZJQqu"
  },
  {
    "id": "14",
    "category": "For Kids",
    "price": "20$",
    "sale": "10%",
    "brand": "Hopscotch",
    "size": "XS/S/M",
    "name": "T-Shirt & Shorts Set",
    "reviews": "5",
    "description": "Soft cotton T-shirt and shorts for boys, suitable for summer play.",
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTezds8qb_RObu7GbCC6YPo1SKpK5v_u13LN8tAEIWseCz2vCn6TRbhg6XPSF01CgS498JTwj5c-BhdZp0yt6EIl-BWGMBMy-6quHXZp-qWruCeCeqlCvvW"
  },
  {
    "id": "15",
    "category": "For Kids",
    "price": "25$",
    "sale": "12%",
    "brand": "Cucumber",
    "size": "XS/S",
    "name": "Girls Floral Frock",
    "reviews": "5",
    "description": "Adorable frock with flower prints, perfect for toddlers.",
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT8i8I47GShqY2gHTrpuoC4FvPFUSI-hPlWawOYmBJnhAqYABH5n9ZxOoZTKBM5-Gd7Ikt7Q6cOwVRDjNfHKzBfqaIFmMSwY_lB5dURaG04r9-V3kqXjxp9xA"
  }
];

export default data;
